
<table class="table-view  table" cellspacing=0 >
  <tr>
    <th>ekuid</th>
    <td>eku_id</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>pid</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>pname</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>unit</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>num</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>action</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>action_label</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>alert_level</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>kuwei</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>datetime</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>doer</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>remark</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>category</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>balance</td>
  </tr>
  <tr>
    <th>ekuid</th>
    <td>cur_balance</td>
  </tr>
</table>
